### ISSUE TITLE
请问该项目有对应的论文吗

### ISSUE THREAD

**Issue by Fangzehaoa** [daniprec/ocean-route-optimization#18]
自学船舶路径优化的部分，但是苦于没有代码基础，所以想通过一些已有成果去学习研究，融入自己的项目内容。

**Comment by daniprec** [comment]
我们尚未发布任何论文，但我鼓励您在这里关注当前项目版本的更新：https://weathernavigation.com/

**Comment by Fangzehaoa** [comment]
thank you



---- 回复的原邮件 ----
| 发件人 | Daniel Precioso, ***@***.***> |
| 日期 | 2023年11月08日 16:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [UCA-Datalab/ocean-route-optimization] 请问该项目有对应的论文吗 (Issue #18) |

Closed #18 as completed.
