### ISSUE TITLE
Dimensionalidad y estandarización de los vectores

### ISSUE THREAD

**Issue by borjasanlei** [daniprec/ocean-route-optimization#4]
# Problema

Tenemos un espacio discretizado en MxN  puntos. Datos de corrientes y velocidades pueden seguir discretizaciones distintas en tamaño. Además, en función de la magintud que se esté tratando el problema puede tener diferente dimensionalidad.

# Dimensiones

Para cualquier magnitud que tratemos vamos a tener, al menos, 3 dimesiones: 2 espaciales (siempre) y 1 dimensión referente a la magnitud. tensores

# Proposición
Propongo estandarizar los tensores que compartamos y manejemos de la siguiente manera:

+ Primera dimensión: Latitud (M puntos de la discretización)
+ Segunda dimensión: Longitud (N puntos de la discretización)
+ Tercera dimensión: Profundidad de K capas, una por cada dimensión de la magnitud

Por tanto, tendríamos K matrices de MxN elementos

**Comment by borjasanlei** [comment]
Representación en arrays:

```python
# Valores aleatorios para una magnitud (por ejemplo, modulo de la velocidad de las corrientes)
lat_points = 30
long_points = 20
streams_velocities = np.random.rand(lat_points, long_points, 1)
```

**Comment by daniprec** [comment]
Muy buena idea, que todos los tensores sigan la misma dimensionalidad para latitud y longitud va a ser muy importante y agilizará el cálculo de velocidades y trayectorias. A la larga nos interesará una función que tome una matriz con una escala cualquiera y la estandarice a la escala común
